### ISSUE TITLE
Add nice icons for the workflow items in the VSM editor

### ISSUE THREAD

**Issue by pcdavid** [ObeoNetwork/Jarvis#19]
It's a small thing, but the ugly default EMF icons tend to leave a bad impression to viewers, and it shouldn't be difficult to find icons for the few concepts we have: Workflow, Page, Section, Activity.

**Comment by pcdavid** [comment]
Proposal:

![selection_001](https://user-images.githubusercontent.com/10608/32440561-fc1c6870-c2f3-11e7-8318-dc2173dd6faf.png)

It can certainly be improved, but with such generic concepts as "Workflow", "Page", "Section" and "Activity", its difficult to be very explicit. And I think even these are better than the ugly default "colored stars".

**Comment by pcdavid** [comment]
I'm changing the scope a little: in addition to the icons (done), we should also review the label providers. At the very least the "Description" suffix is useless in this context.

**Comment by sbegaudeau** [comment]
Honestly it looks nice, I'm in favor of closing this issue for now.
