### ISSUE TITLE
Create a proper sample model

### ISSUE THREAD

**Issue by pcdavid** [ObeoNetwork/Jarvis#23]
We should have a proper sample model in a plug-in. It could try to mimic the "standard" workflow and activities defined in Capella, instead of "Item1", "Item2" etc.

**Comment by sbegaudeau** [comment]
What kind of DSL should we used as the sample odesign?

**Comment by pcdavid** [comment]
You mean for the actual modeler? I guess Ecore should be enough, my point is just that for a demo/video, it would be nicer to have pages named "Operational Analysis", "System Analysis" witht the corresponding descriptions, section titles etc. instead of "lorem ipsum" and "Section X".

**Comment by sbegaudeau** [comment]
Yes I was wondering about the actual designer. Ecore should be enough indeed 👍

**Comment by sbegaudeau** [comment]
I have improved the sample model:
* The labels of some elements has been improved to prevent some overflow issues in the front-end (I tried using text-overflow: ellipsis but it did not work as I was expecting, I would have to retry later)
* I have also added multiple activities in the pages

**Comment by sbegaudeau** [comment]
We will need to update a tiny bit more the example and then we will have a first version that we can use for the demo.

**Comment by sbegaudeau** [comment]
I'm closing this issue now that the first presentation has been done.
