### ISSUE TITLE
Configure the build

### ISSUE THREAD

**Issue by sbegaudeau** [ObeoNetwork/Jarvis#5]
Some key elements are missing to have a proper build like:
* a feature
* an update site
* the pom.xml

The build should be triggered using a Travis-based configuration for now.

**Comment by sbegaudeau** [comment]
A target platform should be configured with Google Gson for the serialization.

**Comment by sbegaudeau** [comment]
The Travis configuration is missing

**Comment by sbegaudeau** [comment]
I won't close this issue for now since an administrator is required to activate the Travis support for this Github repository.

**Comment by mbats** [comment]
I just activated the Travis build. Next push should trigger build! Have fun :)

**Comment by sbegaudeau** [comment]
Closing this since the build is now up and running. I'll still have to configure a couple a things for the CRA integration but I'll track this work using another issue.

🚀
